apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    description: Build and run Scala and Java applications using SBT
    iconClass: icon-scala
    openshift.io/display-name: SBT
  generation: 4
  name: sbt
  namespace: openshift
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      description: Build and run Scala and Java applications using SBT
      iconClass: icon-scala
      openshift.io/display-name: SBT
      openshift.io/provider-display-name: https://github.com/jw3/sbt-s2i
      sampleRepo: https://github.com/theiterators/akka-http-microservice
      supports: sbt:2.12.7,java,scala
      tags: builder,java,scala
      version: "2.12.7"
    from:
      kind: DockerImage
      name: jwiii/sbt-s2i:1.2.3-2.12.7
    generation: 1
    importPolicy: {}
    name: "2.12.7"
    referencePolicy:
      type: Source
